#!/bin/bash

function tree(){
height_tree=$1
width_snow=$2

flag=0

if (( height_tree < width_snow )); then
    echo "Висота ялинки має бути більша за ширину снігу." >&2
    exit 1
elif (( height_tree < 8 || width_snow < 7 )); then
    echo "Параметри не підходять для побудови ялинки." >&2
    exit 1
elif (( width_snow <= 0 || height_tree <= 0 )); then
    echo "Значення мають бути додатніми." >&2
    exit 1
elif (( width_snow < height_tree-2 )); then
    echo "Ширина має бути такою ж як ширина яруса ялинки." >&2
    exit 1
elif (( (( width_snow==height_tree ))&&(( height_tree%2!=0 && width_snow%2!=0 )) )); then
    echo "Помилка! Неможливо побудувати ялинку." >&2
    exit 1
elif (( (( width_snow%2==0 && height_tree%2==0 )) && ((width_snow < height_tree-1)) )); then
    echo "Помилка! Неможливо побудувати ялинку." >&2
    exit 1
else
    if ((width_snow%2==0)); then
        p=1
    else
        p=0
    fi
    mid=width_snow/2
    for (( i=1; i<=height_tree/2-1; i++ )); do
        for (( j=1; j<=mid-i+1-p; j++ )); do
            echo -n " "
        done
        for (( k=1; k<=2*i-1; k++ )); do
            if (( i%2==0 )); then
                echo -n "#"
                flag=0
            else
                echo -n "*"
                flag=1
            fi
        done
        echo
    done
    i=1
    while (( i<=height_tree/2-2 )); do
        j=1
        until (( j>mid-i-p )); do
            echo -n " "
            (( j++ ))
        done
        if (( flag==1 )); then
            k=1
            until (( k>2*i+1 )); do
                echo -n "#"
                (( k++ ))
            done
            flag=0
        else
            k=1
            until (( k>2*i+1 )); do
                echo -n "*"
                (( k++ ))
            done
            flag=1
        fi
        echo
        (( i++ ))
    done
    for i in 1  2; do
        for (( j=1; j <=mid-1-p; j++ )); do
            echo -n " "
        done
        for k in {1..3}; do
            echo -n "#"
        done
        echo
    done
        for (( i=1; i <=width_snow-p; i++ )); do
            echo -n "*"
        done
    echo
fi
}
tree $1 $2
